# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyangyuPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod	'SnapKit'
  pod	'RxSwift'
  pod 	'RxCocoa'
  pod	'SwiftLint'
  pod 	'Then'
  pod   'Kingfisher'
  pod	'IQKeyboardManager'

  # Pods for HyangyuPractice

  target 'HyangyuPracticeTests' do
    inherit! :search_paths
    # Pods for testing
    pod	'RxTest'
    pod 'RxSwift'
    pod 'RxRelay'
  end

  target 'HyangyuPracticeUITests' do
    # Pods for testing
    pod 'RxTest'
    pod 'RxSwift'
    pod 'RxRelay'
  end

end
